[package]
name = "operation-queue"
version = "0.1.0"
authors = ["Roustem <roustem@1password.com>"]
edition = "2018"

[dependencies]
rusqlite = { version = "0.23" }
tokio = { version = "0.2", default-features = false, features = ["rt-threaded", "macros", "sync"] }